ACTION_CLASS_WORDS = {

    "refund": [
        "refund",
        "issue a refund",
        "get a refund",
        "money back",
        "reimbursement",
        "reverse the charge",
        "reverse payment",
        "chargeback",
        "incorrect charge",
        "wrong charge",
        "double charged",
        "charged twice",
        "overcharged",
        "billing error",
        "unauthorized charge",
        "why was I charged",
        "never received but charged"
    ],

    "exchange": [
        "exchange",
        "exchange item",
        "exchange my order",
        "request an exchange",
        "item exchange",
        "product exchange",
        "replace",
        "replace item",
        "replace my item",
        "replacement",
        "need a replacement",
        "send a replacement",
        "wrong size",
        "size too small",
        "size too big",
        "different size",
        "wrong color",
        "different color",
        "wrong variant",
        "received the wrong item",
        "item mismatch",
        "incorrect item received",
        "not the item I ordered",
        "defective item replace",
        "replace defective item",
        "swap item",
        "swap for another",
        "change to another size",
        "change to another color",
        "can I exchange this",
        "how to exchange",
        "exchange process",
        "exchange policy",
        "exchage"  # typo
    ],

    "return": [
        "return",
        "return item",
        "return my order",
        "return this product",
        "start a return",
        "initiate return",
        "return request",
        "process a return",
        "send back",
        "ship back",
        "send the item back",
        "return package",
        "how to return",
        "return process",
        "return instructions",
        "return label",
        "need a return label",
        "provide return label",
        "return authorization",
        "return approval",
        "return policy",
        "want to send it back",
        "I want to return this",
        "can I return this",
        "return window",
        "is it eligible for return",
        "wrong item want to return",
        "product not suitable",
        "don’t want this item anymore"
    ],

    "order_status": [
        "order status",
        "where is my order",
        "where is my package",
        "track order",
        "tracking number",
        "delivery status",
        "shipping status",
        "has it shipped",
        "when will it arrive",
        "estimated delivery",
        "still not received",
        "not delivered yet"
    ],

    "cancel_order": [
        "cancel",
        "cancel order",
        "stop order",
        "void order",
        "ordered by mistake"
    ],

    "complaint": [
        "not satisfied",
        "very disappointed",
        "bad experience",
        "unacceptable",
        "frustrated"
    ]
}
